apiVersion: apps/v1
kind: Deployment
metadata:
  name: ownid-server
spec:
  template:
    spec:
      containers:
        - name: ownid-server # (1)
          env:
            - name: OWNID__CALLBACK_URL
              value: https://skipthepassword.dev.ownid.com
            - name: OWNID__DID
              value: did:ownid:demo_dev_2_151850889514
            - name: OWNID__NAME
              value: Skip The Password (Demo 2)
            - name: OWNID__DESCRIPTION
              value: Skip The Password (Demo 2)
            - name: OWNID__FIDO2_PASSWORDLESS_PAGE_URL
              value: https://passwordless.demo.dev.skipthepassword.com
            - name: OWNID__TOP_DOMAIN
              value: demo.dev.skipthepassword.com
