apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-gigya
spec:
  template:
    spec:
      containers:
        - name: server-gigya
          env:
            - name: OWNID__WEB_APP_URL
              value: https://sign.staging.ownid.com
            - name: OWNID__ADD_CORS_ORIGINS
              value: https://demo-screens.staging.ownid.com
            - name: ASPNETCORE_ENVIRONMENT
              value: staging
            - name: SERILOG__MINIMUMLEVEL__DEFAULT
              value: Debug
            - name: SMTP__HOST
              valueFrom:
                secretKeyRef:
                  name: demo-smtp-secret
                  key: host
            - name: SMTP__USER_NAME
              valueFrom:
                secretKeyRef:
                  name: demo-smtp-secret
                  key: user-name
            - name: SMTP__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo-smtp-secret
                  key: password
            - name: SMTP__SSL
              value: 'true'
            - name: SMTP__FROM_ADDRESS
              value: no-reply@skipthepassword.com
            - name: SMTP__FROM_NAME
              value: Magic Link - STAGING            
            - name: SERILOG__MINIMUMLEVEL__DEFAULT
              value: Debug