apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-gigya
spec:
  template:
    spec:
      containers:
        - name: server-gigya
          env:
            - name: OWNID__CALLBACK_URL
              value: https://server.demo3.dev.ownid.com
            - name: OWNID__DID
              value: did:ownid:demo_dev_3_151850889514
            - name: OWNID__NAME
              value: Noted (OwnID Demo 3)
            - name: OWNID__DESCRIPTION
              value: Noted (OwnID Demo 3)
            - name: OWNID__FIDO2_FALLBACK_BEHAVIOR
              value: Block
            - name: OWNID__FIDO2_PASSWORDLESS_PAGE_URL
              value: https://passwordless.demo3.dev.ownid.com
            - name: OWNID__TOP_DOMAIN
              value: demo3.dev.ownid.com
            - name: OWNID__MAGIC_LINK__ENABLED
              value: 'false'
            - name: OWNID__MAGIC_LINK__REDIRECT_URL
              value: https://demo3.dev.ownid.com/login
